name: CI

on:
  push:
    branches:
      - master
    tags: [ "*" ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Build and Publish to Local
        run: sbt compile